version: '2'

services:
  base:
    image: node:14
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service

  dev:
    extends:
      service: base
    container_name: fastify-router-oas-dev
    command: "yes"

  install:
    extends:
      service: base
    command: yarn install --network-concurrency 1

  build:
    extends:
      service: base
    command: yarn run build